# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
